name: MergeDeploy
on:
  push:
    branches:
      - deploy
  pull_request:
    types: [closed]
jobs:
  build:
    name: MergeDeploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 16.17.1
      - name: Install pnpm
        run: npm i pnpm@8.5.1 -g
      - name: Install dependencies
        run: pnpm i --frozen-lockfile
      - name: Release Applique
        run: npm run release
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        
