name: Release using release-please
on:
  push:
    branches:
      - deploy
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v4
        id: release
        with:
          release-type: node
      # The logic below handles the npm publication:
      - uses: actions/checkout@v4
        # these if statements ensure that a publication only occurs when
        # a new release is created:
        if: ${{ steps.release.outputs.release_created }}
      - uses: actions/setup-node@v3
        with:
          node-version: 16.17.1
          registry-url: 'https://registry.npmjs.org'
        if: ${{ steps.release.outputs.release_created }}
      # - name: Set Auth token
      #   run: npm config set //registry.npmjs.org/:authToken="${{ secrets.NODE_AUTH_TOKEN }}"
      - name: Install pnpm
        run: npm i pnpm@8.5.1 -g
      - name: Install dependencies
        run: pnpm i --frozen-lockfile
      - run: npm run :publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
        if: ${{ steps.release.outputs.release_created }}
          
