name: Release
on:
  release:
    types: [published]
jobs:
  release:
    name: Publish to npmjs
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Set user and email
        run: git config user.name github-actions && git config user.email github-actions@github.com
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: 16.17.1
          registry-url: 'https://registry.npmjs.org'
      - name: Install pnpm
        run: npm i pnpm@8.5.1 -g
      - name: Install dependencies
        run: pnpm i --frozen-lockfile
      - run: npm run release
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
